### ISSUE TITLE
Error in MacOS Big Sur 11.4

### ISSUE THREAD

**Issue by Mfernand** [benjifs/bitbar-slack-team-notifications#11]
![image](https://user-images.githubusercontent.com/3799998/125812549-e493b73c-f43f-4606-9b7d-371159279f5b.png)
I get this error using xbar 2.1.4-beta on MacOS Big Sur 11.4.

I'm using the legacy token of slack and it work in the terminal when I do: 
`node slack-team-notifications.1m.js `
But the xbar icon show thit error when i have unread messages. When I have no unread message works fine.

**Comment by benjifs** [comment]
Sorry about that. Fixed it locally and completely forgot to push my changes. It's related to the switch from bitbar to xbar as the `bash` parameter was renamed `shell`.

I just updated this repo so try v1.1.2 and let me know if that fixes the issue for you. I'll submit a PR to the main plugin repo shortly.

**Comment by benjifs** [comment]
Fixed as of v1.1.2 and PR was merged in matryer/xbar-plugins#1664

**Comment by Mfernand** [comment]
That it's, now works. 

Thanks you
