### ISSUE TITLE
Incorrect channel count

### ISSUE THREAD

**Issue by futzlarson** [benjifs/bitbar-slack-team-notifications#2]
I got it working, but it shows 2 messages in #general which is incorrect (no messages are unread):

![image](https://user-images.githubusercontent.com/1168673/102546390-9041ee00-4085-11eb-9d54-e29b906c867c.png)

![image](https://user-images.githubusercontent.com/1168673/102546296-6b4d7b00-4085-11eb-80ff-b2714d0f8d38.png)

Thoughts? Still doing this an hour later.

Update: Fixing the permissions errors didn't fix this. A new message came in (in a different channel) and that _did_ appear correctly. So far just #general seems wonky. Even clicking `Mark all as read` doesn't clear it. I remember I ran into this about a year ago as well, either this plugin or another.

**Comment by benjifs** [comment]
I've seen this happen too and in my experience it's been related to threads. I just tested and it seems like they changes timestamp at some point the past year. They're also going to deprecate `im.mark` for marking as read so I'm working on replacing it with `conversations.mark`.

In the meantime, try the following to see if it fixes it for you:
In `slack-team-notifications.1m.js` line 101, change to:
```
'ts': Math.floor(Date.now() / 1000) + '.000000'
```
and see if that marks things as read.

Let me know if that works for you

**Comment by futzlarson** [comment]
Nope. Ran it twice and even quit BitBar. Can you ignore thread counts? Weird, because the threads are also all read.

**Comment by futzlarson** [comment]
Strangely, for no reason I can discern, it now correctly shows zero (meaning the workspace doesn't show at all). Let's see if it comes back.

**Comment by futzlarson** [comment]
So far, so good. I wonder if marking as read had a delayed effect?

**Comment by benjifs** [comment]
I noticed the delayed effect too once and haven't seen it since. But `Mark as read` seems to be working with the timestamp change. It's also available in the [fix-markasread-ui](https://github.com/benjifs/bitbar-slack-team-notifications/tree/fix-markasread-ui) branch

**Comment by futzlarson** [comment]
Still seems okay. I'll reopen if it happens again. Thanks!
