### ISSUE TITLE
Permissions errors

### ISSUE THREAD

**Issue by futzlarson** [benjifs/bitbar-slack-team-notifications#3]
![image](https://user-images.githubusercontent.com/1168673/102546537-caab8b00-4085-11eb-85a0-0761a5e6440a.png)

But when I go to permissions, the only match I see is for `admin:conversations:`

![image](https://user-images.githubusercontent.com/1168673/102546587-e020b500-4085-11eb-8d84-e45fc36d89c3.png)

Hoping to resolve this as I would love to have a menu bar app that displays status for all the Slack workspaces I have.

**Comment by futzlarson** [comment]
Figured it out. Adding `channels:history`, `groups:history` and `mpim:history` cleared the errors. If the README is updated with those, this can be closed.

**Comment by benjifs** [comment]
Weird, I'm not seeing those errors. I might have to try a few different types of notifications. It seems to be causes by `conversation.history` being deprecated so I'll add those permissions in the `README` but will also move away from the deprecated call.

**Comment by futzlarson** [comment]
Yeah might be notif type. Maybe trigger a list of all of them and see what you get?

**Comment by benjifs** [comment]
I was finally able to replicate this issue by creating a new app and setting everything up from scratch. The app I have created for the sample for some reason doesn't require these scopes but new apps do.

I have added these new scopes to the README. Thanks for the help.

**Comment by futzlarson** [comment]
Thanks!
