### ISSUE TITLE
Slack API: Deprecating usage of token as a query string parameter in Web API requests

### ISSUE THREAD

**Issue by npazo** [benjifs/bitbar-slack-team-notifications#8]
https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps

>On February 24, 2021, we will stop allowing newly created Slack apps to send requests to Web API methods with access tokens presented in a URL query string. Instead, apps must send tokens in the Authorization HTTP header or alternatively as a URL-encoded POST body parameter.

After banging my head against the wall for a few hours trying to figure out why this won't work, I discovered this Slack API change.

**Comment by npazo** [comment]
I don't know Node at all, but from I can tell should be fairly easy fix. I tried to hack it together. Basically add `.auth(token, { type: 'bearer' })` to the request and remove `token` as a parameter. Probably going to need some code cleanup to remove all of that.

**Comment by benjifs** [comment]
Good catch! Since most of my apps have been set up for a few years, I haven't seen this issue at all. I just made this change + cleaned up some code and it seems to be working for both old and new apps. Let me know if the latest release works for you and we can close this issue if its fixed

**Comment by npazo** [comment]
Seems to be working. Thanks for the quick fix!!!
